# Generated by Django 2.0.2 on 2018-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.TextField()),
                ('method', models.CharField(max_length=50)),
                ('metadata', models.TextField()),
                ('success', models.BooleanField()),
                ('error', models.TextField()),
                ('execution_time_millis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('submissions.job',),
        ),
    ]
