# Generated by Django 2.0.2 on 2018-02-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='execution_time_millis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='metadata',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='job',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
