# Generated by Django 2.0.2 on 2018-03-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_remove_solution_pending'),
        ('submissions', '0002_auto_20180305_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='job',
            name='method',
        ),
        migrations.AddField(
            model_name='job',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Solution'),
        ),
    ]
