# Generated by Django 2.0.2 on 2018-03-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_remove_solution_pending'),
        ('submissions', '0003_auto_20180305_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='solution',
        ),
        migrations.AddField(
            model_name='job',
            name='testcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.TestCase'),
        ),
    ]
