# Generated by Django 2.0.2 on 2018-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=100)),
                ('output', models.TextField()),
                ('pending', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
