# Generated by Django 2.0.2 on 2018-03-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_remove_problem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.User'),
        ),
    ]
