# Generated by Django 2.0.2 on 2018-03-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_problem_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='pending',
        ),
    ]
