# Generated by Django 2.0.2 on 2018-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20180305_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(null=True),
        ),
    ]
