# Generated by Django 2.0.2 on 2018-03-06 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20180306_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restapi.Problem'),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewer_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='review date'),
        ),
    ]
