# Generated by Django 2.0.2 on 2018-04-02 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_auto_20180307_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=100)),
                ('output', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partialSolutions', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partialSolutions', to='restapi.Problem')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
